apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -c -f latest.yml --namespace {{ .Values.NAMESPACE }}
    kompose.version: 1.38.0 (a8f5d1cbd)
  labels:
    io.kompose.service: nextcloud-aio-redis
  name: nextcloud-aio-redis
  namespace: {{ .Values.NAMESPACE }}
spec:
  ports:
    - name: "6379"
      port: 6379
      targetPort: 6379
  selector:
    io.kompose.service: nextcloud-aio-redis
